apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-myservicea
  namespace: weave
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: dashboard.hadtech-platform.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: weave-weave-scope
          servicePort: 80
      
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-myserviceb
  namespace: monitoring
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: monitor.hadtech-platform.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
